@startuml Graph Coloring with ASP
top to bottom direction

actor User
'actor Modeler
actor "ASP Solver (Clasp)" as Solver
package "ASP Graph Coloring System" {
    usecase "Input graph" as graph
    usecase "Input bio data" as data
    usecase "Input rules" as rules
    usecase "Generate instances" as inst
    usecase "Filter instances" as filter
    usecase "Get solutions" as solution
    usecase "Problem solving" as solving
    User -> graph
    User -> data
    'Modeler -> rules
    User -> solution
    Solver -> solving
    filter --> inst : <<includes>>
    inst --> graph : <<includes>>
    inst --> data : <<includes>>
    solving --> filter : <<includes>>
    solving --> rules : <<includes>>
    solution --> solving : <<extends>> (if solutions exist)
}

@enduml